# Generated by Django 2.0 on 2018-11-12 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181112_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='group',
            new_name='project',
        ),
    ]
