# Generated by Django 2.0 on 2018-11-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181112_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='disable',
            field=models.IntegerField(default=0),
        ),
    ]
